apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
  name: fluentd
  namespace: logstress
spec:
  ports:
  - port: 24231
    protocol: TCP
    targetPort: 24231
    name: web
  selector:
    app: fluentd
  type: ClusterIP
