[sources.kube]
  type = "kubernetes_logs"
  auto_partial_merge = true
  glob_minimum_cooldown_ms = 360000
  exclude_paths_glob_patterns = ["/var/log/containers/*_openshift-logging_*.log"]
  # extra_label_selector = "type=log-stressor"

[sinks.stress]
  type="blackhole"
  inputs = ["kube"]
  # encoding.codec = "ndjson"
  # path = "/var/log/containers/stress.log"

[sources.internal_metrics]
  type = "internal_metrics"

[sinks.prom_exporter]
  type = "prometheus"
  inputs = ["internal_metrics"]
  address = "0.0.0.0:24231"