apiVersion: v1
kind: Service
metadata:
  labels:
    app: collector
  name: collector
  namespace: logstress
spec:
  ports:
  - port: 24231
    protocol: TCP
    targetPort: 24231
    name: web
  selector:
    component: collector
    logging-infra: collector
    provider: openshift
  type: ClusterIP