apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: collector-monitor
  name: collector-monitor
  namespace: logstress
spec:
  endpoints:
  - interval: 5s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: collector